method: random
metric:
  goal: minimize
  name: val_loss
parameters:
  accumulation_step:
    distribution: categorical
    values:
      - 1
      - 2
      - 4
      - 8
      - 16
  dropout_rate:
    distribution: uniform
    max: 0.5
    min: 0
  epochs:
    distribution: constant
    value: 10
  learning_rate:
    distribution: log_uniform_values
    max: 0.1
    min: 1e-05
  optimizer:
    values:
      - adam
      - sgd
      - adamw
  siamese_embedding_size:
    distribution: categorical
    values:
      - 16
      - 32
      - 64
      - 128
  weight_decay:
    distribution: categorical
    values:
      - 0.1
      - 0.01
      - 0.001
      - 0.0001
      - 0
